dimensions: {
  wheel_diameter: 0.095,
  diff: 0.22,
  width: 0,
  height: 0
}


robot_state_publisher:
  type: robot_state_publisher/RobotStatePublisher
  publish_rate: 50
  source_list:
  - "joint_states/left_wheel_hinge"
  - "joint_states/right_wheel_hinge"
joy_node/dev: "/dev/input/js1"
camera_topic: "/usb_cam_node/image_raw"
cmd_vel_topic: "/cmd_vel"
ultrasonic_sensor_topic: "/ultrasonic"
radar_topic: "/radar/scan"
odom_topic: "/odom"
base_link_topic: "/chassis"
battery_topic: "/battery_state"
imu_topic: "/imu"
buffer_size: 2
encoder_ticks: 360
length_between_two_wheels: 0.22
servo: 0
euclidean_distance: 200
euclidean_color:
  - 0
  - 0
  - 255
hsv_low:
  - 0
  - 0
  - 0
hsv_high:
  - 100 # out of h 0...180
  - 255
  - 255
contour_area_min: 7000
# tD: 95
luminocity_up: 120
luminocity_low: 60
gpio_list_trigger :
  - 1
  - 12
  - 16
  - 20
  - 21
gpio_list_echo:
  - 5
  - 6
  - 13
  - 19
  - 26
positions:
  - "left"
  - "front_left"
  - "front"
  - "front_right"
  - "right"
rate: 15 # can also be  dynamically calculated based on various nodes' preformance
joint_frames:
  - "left_wheel"
  - "right_wheel"

port: "/dev/ttyACM0"
baud: 57600
